spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_blog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    username: blogjava1@gmail.com
    password: ${JAVA_BLOG_EMAIL_PASS}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    whitelabel:
      enabled: true